# coding: utf-8

"""
    Art Search API

    Art Search let's you search and discover over one million pieces of historic art.

    The version of the OpenAPI document: 1.0.0
    Contact: mail@artsearch.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "artsearch"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Art Search API",
    author="David Urbansky",
    author_email="mail@artsearch.io",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Art Search API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Art Search let&#39;s you search and discover over one million pieces of historic art.
    """,  # noqa: E501
    package_data={"artsearch": ["py.typed"]},
)
