"""
Random User Generator Tool - مولد مستخدمين عشوائيين
"""
import httpx
from typing import Dict, Any
from .base import BaseTool


class RandomUserTool(BaseTool):
    """
    أداة توليد بيانات مستخدمين عشوائية
    """
    @property
    def name(self) -> str:
        return "/randomuser"
    
    @property
    def description(self) -> str:
        return "👤 مستخدم عشوائي - بيانات مستخدم وهمية للاختبار"
    
    @property
    def cost(self) -> int:
        return 10
    
    async def execute(self, user_input: str, user_id: str) -> Dict[str, Any]:
        """
        توليد بيانات مستخدم عشوائي
        """
        
        try:
            url = "https://randomuser.me/api/"
            
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.get(url)
                response.raise_for_status()
                data = response.json()
            
            if not data.get("results"):
                return {
                    "status": "error",
                    "output": "❌ فشل في توليد مستخدم",
                    "tokens_deducted": 0
                }
            
            user = data["results"][0]
            
            # المعلومات الشخصية
            title = user["name"]["title"]
            first = user["name"]["first"]
            last = user["name"]["last"]
            gender = user["gender"].capitalize()
            
            # معلومات الاتصال
            email = user["email"]
            phone = user["phone"]
            cell = user["cell"]
            
            # العنوان
            street_num = user["location"]["street"]["number"]
            street_name = user["location"]["street"]["name"]
            city = user["location"]["city"]
            state = user["location"]["state"]
            country = user["location"]["country"]
            postcode = user["location"]["postcode"]
            
            # معلومات إضافية
            dob = user["dob"]["date"][:10]
            age = user["dob"]["age"]
            username = user["login"]["username"]
            password = user["login"]["password"]
            picture = user["picture"]["large"]
            
            output = f"""👤 **Random User Profile**

![Profile Picture]({picture})

**Personal Info:**
👤 **Name:** {title} {first} {last}
⚧️ **Gender:** {gender}
🎂 **Age:** {age} (Born: {dob})

**Contact:**
📧 **Email:** {email}
📞 **Phone:** {phone}
📱 **Cell:** {cell}

**Address:**
🏠 {street_num} {street_name}
🏙️ {city}, {state}
🌍 {country} - {postcode}

**Login Credentials:**
👤 **Username:** `{username}`
🔒 **Password:** `{password}`

---
🎲 Generated by RandomUser.me API
⚠️ This is fake data for testing purposes only"""
            
            return {
                "status": "success",
                "output": output,
                "tokens_deducted": self.cost
            }
            
        except Exception as e:
            return {
                "status": "error",
                "output": f"❌ خطأ: {str(e)}",
                "tokens_deducted": 0
            }
