# coding: utf-8

"""
    Art Search API

    Art Search let's you search and discover over one million pieces of historic art.

    The version of the OpenAPI document: 1.0.0
    Contact: mail@artsearch.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from artsearch.models.search_artworks200_response_artworks_inner import SearchArtworks200ResponseArtworksInner

class TestSearchArtworks200ResponseArtworksInner(unittest.TestCase):
    """SearchArtworks200ResponseArtworksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchArtworks200ResponseArtworksInner:
        """Test SearchArtworks200ResponseArtworksInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchArtworks200ResponseArtworksInner`
        """
        model = SearchArtworks200ResponseArtworksInner()
        if include_optional:
            return SearchArtworks200ResponseArtworksInner(
                title = '',
                image = '',
                id = 56
            )
        else:
            return SearchArtworks200ResponseArtworksInner(
        )
        """

    def testSearchArtworks200ResponseArtworksInner(self):
        """Test SearchArtworks200ResponseArtworksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
