# coding: utf-8

"""
    Art Search API

    Art Search let's you search and discover over one million pieces of historic art.

    The version of the OpenAPI document: 1.0.0
    Contact: mail@artsearch.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from artsearch.api.art_api import ArtApi


class TestArtApi(unittest.TestCase):
    """ArtApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtApi()

    def tearDown(self) -> None:
        pass

    def test_random_artwork(self) -> None:
        """Test case for random_artwork

        Random Artwork
        """
        pass

    def test_retrieve_artwork_by_id(self) -> None:
        """Test case for retrieve_artwork_by_id

        Retrieve Artwork by Id
        """
        pass

    def test_search_artworks(self) -> None:
        """Test case for search_artworks

        Search Artworks
        """
        pass


if __name__ == '__main__':
    unittest.main()
